"""empty message

Revision ID: a553b4f0e4fc
Revises: 6eb479788452
Create Date: 2022-09-03 10:13:33.779165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a553b4f0e4fc'
down_revision = '6eb479788452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time1', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time1')
    # ### end Alembic commands ###
